# Generated by Django 3.1.5 on 2021-01-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210116_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='client',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='detsale',
            table='detalle_venta',
        ),
        migrations.AlterModelTable(
            name='product',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='venta',
        ),
    ]
